Tutorial/objects 1160
SMARTRACTECHNOLOGY/smartcosmos-devkit pull request #23
Opened 2017-01-06 14:09 UTC by jbauerrfid

### What changes were proposed in this pull request?

* add tutorial for creating initial data (new tenant, first user, some things and relationships)
* added example shell scrips and JSON files for the request bodies

### How is this patch documented?

* README.adoc

### How was this patch tested?

* Tested with local devkit installation and included bash scrips on Ubuntu. Should be tested on Mac too by reviewer (I do not have the Apple hardware available).

#### Depends On

None.

2017-01-06 15:15 UTC, sdomula requested changes

2017-01-09 09:30 UTC, andreassiegel requested changes
Added some more or less general remarks on style and some wording.

However, this should definitely be checked by a native speaker, especially since we have many of them available. 😎

2017-01-09 13:44 UTC, andreassiegel approved these changes

2017-01-09 15:48 UTC, sdomula approved these changes
Great work! 🎉

2017-01-09 15:50 UTC, sdomula requested changes

2017-01-09 16:32 UTC, sdomula approved these changes

2017-01-10 07:16 UTC, merged