Feature/add interaction config
SMARTRACTECHNOLOGY/smartcosmos-devkit pull request #50
Opened 2017-02-03 12:52 UTC by jbauerrfid

### What changes were proposed in this pull request?

* add configuration for smartcosmos-ext-interactions
* add API link for smartcosmos-ext-interactions

#### Depends On

* https://github.com/SMARTRACTECHNOLOGY/smartcosmos-ext-interactions/pull/8

2017-02-03 13:26 UTC, sdomula requested changes

2017-02-03 13:26 UTC, sdomula commented on config/smartcosmos-ext-interactions.yml
> +  port: 45556
shouldn't the port be set like this `port: ${smartcosmos.service.ext-interactions.port}`

2017-02-03 13:26 UTC, sdomula commented on docker-compose.yml
> +version: '3'
Why?? Docker compose file format is at version 2. Why do you increase the version here?

2017-02-03 13:34 UTC, andreassiegel commented on config/smartcosmos-ext-interactions.yml
> +  port: 45556
yes

2017-02-03 13:39 UTC, sdomula requested changes

2017-02-03 13:39 UTC, sdomula commented on config/smartcosmos-ext-interactions.yml
> +
Remove `host` and `port`.

2017-02-03 13:47 UTC, jbauerrfid commented on config/smartcosmos-ext-interactions.yml
> +
updated this also in https://github.com/SMARTRACTECHNOLOGY/smartcosmos-ext-interactions/pull/8

2017-02-03 14:57 UTC, ghost approved these changes

2017-02-03 14:57 UTC, wfschneider-rfid commented on docker-compose.yml
> +version: '3'
I believe this will break docker since this is the version of the compose file.

2017-02-05 12:41 UTC, sdomula requested changes

2017-02-05 12:41 UTC, sdomula commented on config/smartcosmos-ext-interactions.yml
> +  interactions:
If the above settings are default (they should), remove them from this settings file.

2017-04-06 09:13 UTC, sdomula commented
I'll close this PR, as it is not relevant anymore.

2017-04-06 09:13 UTC, closed without merging